services:
    security.authentication_handler:
        class: Youshido\SecurityUserBundle\Service\AuthenticationHandler
        public: false
        arguments: [@router, @session]
        calls:
            - [ setContainer, [ @service_container ]]